receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  
  resource:
    attributes:
      - key: service.name
        value: otel-motel
        action: upsert
      - key: deployment.environment
        value: dev
        action: upsert

exporters:
  # Export logs to Elasticsearch directly (Pipeline 1: OTEL -> ELK)
  elasticsearch/logs:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: otel-motel-otel-direct-logs
    pipeline: otel-motel-logs-ecs
    mapping:
      mode: ecs

  # Export OTLP logs to Elasticsearch in separate index using otlphttp
  elasticsearch/otlphttp:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: otel-motel-otlp-logs

  # Export logs to Vector via OTLP (Pipeline 3: OTEL -> Vector -> ELK)
  otlp/vector:
    endpoint: vector:4319
    tls:
      insecure: true

  # Logging exporter for debugging
  logging:
    verbosity: detailed

extensions:
  health_check:
    endpoint: :13133
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [elasticsearch/logs, elasticsearch/otlphttp, otlp/vector, logging]
